/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercooding.bank.ui;

import com.summercooding.bank.controlleur.Controlleur;
import com.summercooding.bank.entities.Admin;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ingrid
 */
public class JFrameHome extends javax.swing.JFrame {
    Controlleur controlleur = new Controlleur () ;
    private DefaultTableModel DefaultTableModel;

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUtilisateur = new javax.swing.JMenu();
        MenuCreerUtlisateur = new javax.swing.JMenuItem();
        MenuListerUtilisateur = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        MenuCreerUtilisateur = new javax.swing.JMenuItem();
        MenuListerAdmin = new javax.swing.JMenuItem();
        MenuCompte = new javax.swing.JMenu();
        MenuCreerCompte = new javax.swing.JMenuItem();
        MenuListerCompte = new javax.swing.JMenuItem();
        MenuApropos = new javax.swing.JMenu();
        MenuAide = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home page");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuUtilisateur.setText("UTILISATEUR");

        MenuCreerUtlisateur.setText("CREER");
        MenuUtilisateur.add(MenuCreerUtlisateur);

        MenuListerUtilisateur.setText("LISTER");
        MenuUtilisateur.add(MenuListerUtilisateur);

        jMenuBar1.add(MenuUtilisateur);

        MenuAdmin.setText("ADMIN");

        MenuCreerUtilisateur.setText("CREER");
        MenuCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreerUtilisateurActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuCreerUtilisateur);

        MenuListerAdmin.setText("LISTER");
        MenuListerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListerAdminActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuListerAdmin);

        jMenuBar1.add(MenuAdmin);

        MenuCompte.setText("COMPTE");

        MenuCreerCompte.setText("CREER");
        MenuCompte.add(MenuCreerCompte);

        MenuListerCompte.setText("LISTER");
        MenuCompte.add(MenuListerCompte);

        jMenuBar1.add(MenuCompte);

        MenuApropos.setText(" A PROPOS");
        MenuApropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAproposActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuApropos);

        MenuAide.setText("AIDE");
        jMenuBar1.add(MenuAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreerUtilisateurActionPerformed
        // TODO add your handling code here:
        
        
        new JFrameSaveAdmin().setVisible(true);
    }//GEN-LAST:event_MenuCreerUtilisateurActionPerformed

    private void MenuListerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListerAdminActionPerformed
        try {
            /*  try {
            // TODO add your handling code here:ajout des elements dans la base de donnees manuellement
            /* String[] columns = new String []{
            "id" , "Nom" , "login"
            };
            String [][] datas = new String [][]{
            
            {"1" , "toto" , "toto"},
            {"2" , "titi" , "titi"},
            {"3" , "tata","tata"}
            };*/
            
            List<Admin> listAdmin;
            
            listAdmin = controlleur.routeVersListAllAdmin();
            
            DefaultTableModel  model=  new DefaultTableModel();
            
            model.addColumn("Id");
            model.addColumn("id");
            model.addColumn("id");
            
            
            
            for (Admin ad : listAdmin){
                model.addRow(new String [] {ad.getIdadmin() +"" , ad.getNom() , ad.getLogin()});
                
            }
            table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MenuListerAdminActionPerformed

    private void MenuAproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAproposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAproposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuAide;
    private javax.swing.JMenu MenuApropos;
    private javax.swing.JMenu MenuCompte;
    private javax.swing.JMenuItem MenuCreerCompte;
    private javax.swing.JMenuItem MenuCreerUtilisateur;
    private javax.swing.JMenuItem MenuCreerUtlisateur;
    private javax.swing.JMenuItem MenuListerAdmin;
    private javax.swing.JMenuItem MenuListerCompte;
    private javax.swing.JMenuItem MenuListerUtilisateur;
    private javax.swing.JMenu MenuUtilisateur;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
